### ISSUE TITLE
Error during configuration

### ISSUE THREAD

**Issue by pebou** [atrovato/gladys-awox#33]
An error during configuration. Happens after at least one configuration try in the previous minutes. A reboot resolve the issue. Any idea ?

```
0|gladys   |  AwoX module: TypeError: Cannot read property '2a29' of undefined
0|gladys   |     at Gatt.read (/home/pi/gladys/api/hooks/awox/node_modules/noble/lib/hci-socket/gatt.js:502:58)
0|gladys   |     at NobleBindings.read (/home/pi/gladys/api/hooks/awox/node_modules/noble/lib/hci-socket/bindings.js:347:10)
0|gladys   |     at Noble.read (/home/pi/gladys/api/hooks/awox/node_modules/noble/lib/noble.js:309:19)
0|gladys   |     at Characteristic.read (/home/pi/gladys/api/hooks/awox/node_modules/noble/lib/characteristic.js:54:15)
0|gladys   |     at Promise (/home/pi/gladys/api/hooks/awox/lib/bluetooth/read.js:14:22)
0|gladys   |     at Promise._execute (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/debuggability.js:313:9)
0|gladys   |     at Promise._resolveFromExecutor (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/promise.js:483:18)
0|gladys   |     at new Promise (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/promise.js:79:10)
0|gladys   |     at module.exports (/home/pi/gladys/api/hooks/awox/lib/bluetooth/read.js:12:12)
0|gladys   |     at Promise.map.characteristicEntry (/home/pi/gladys/api/hooks/awox/lib/install.js:32:18)
0|gladys   |     at tryCatcher (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/util.js:16:23)
0|gladys   |     at MappingPromiseArray._promiseFulfilled (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/map.js:61:38)
0|gladys   |     at MappingPromiseArray.PromiseArray._iterate (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/promise_array.js:114:31)
0|gladys   |     at MappingPromiseArray.init (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/promise_array.js:78:10)
0|gladys   |     at MappingPromiseArray._asyncInit (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/map.js:30:10)
0|gladys   |     at _drainQueueStep (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/async.js:142:12)
0|gladys   |     at _drainQueue (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/async.js:131:9)
0|gladys   |     at Async._drainQueues (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/async.js:147:5)
0|gladys   |     at Immediate.Async.drainQueues (/home/pi/gladys/api/hooks/awox/node_modules/bluebird/js/release/async.js:17:14)
0|gladys   |     at runCallback (timers.js:789:20)
0|gladys   |     at tryOnImmediate (timers.js:751:5)
0|gladys   |     at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by atrovato** [comment]
It was due to an optimization to avoid complete loading at each message sent.
A condition didn't have any _else_, so the process was locked... then timeout... thne crash...
Now fixed ;)

Same as #35 and #34
